### ISSUE TITLE
Is there going to be a build process for this module?

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/equihash-signature#5]
Node 6 doesn't like async/await

https://github.com/digitalbazaar/equihash-signature/blob/master/lib/EquihashProof2018.js#L14

CI is failing in bedrock-ledger-agent due to this: https://ci.digitalbazaar.com/job/bedrock-ledger-agent/109/console

**Comment by dlongley** [comment]
cc: @davidlehn

**Comment by davidlehn** [comment]
This problem is becoming a hassle! Why is the future so hard to do today?

**Comment by dmitrizagidulin** [comment]
Can we close this issue (since we're no longer supporting Node 6?)

**Comment by dlongley** [comment]
Closed; node 6 won't be supported.
